dist: trusty
sudo: required
language: java

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

osx_image: code8

env:
  - V=0.11.0

cache:
    directories:
     - .bazel_cache
     - tests/.bazel_cache

before_install:
  - ./travis.sh install-bazel

jobs:
  include:
    - stage: annex
      script: ./travis.sh lint
      os: osx
    - stage: annex
      script: ./travis.sh lint
      os: linux

    - stage: annex
      script: ./travis.sh build
      os: osx
    - stage: annex
      script: ./travis.sh build
      os: linux

    - stage: annex
      script: ./travis.sh test
      os: osx
    - stage: annex
      script: ./travis.sh test
      os: linux
