dist: trusty
sudo: required
language: scala

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

env:
  - V=0.11.0

cache:
    directories:
     - .bazel_cache
     - tests/.bazel_cache

before_install:
  - |
    wget https://github.com/bazelbuild/bazel/releases/download/${V}/bazel_${V}-linux-x86_64.deb
    sudo dpkg -i bazel_${V}-linux-x86_64.deb

script:
  - bazel build //...
  - ./setup-tools.sh
  - ./format.sh -mode=check
  - ./test.sh
